# Generated by Django 5.0.2 on 2025-05-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.URLField(default='default.jpg', max_length=500),
            preserve_default=False,
        ),
    ]
