# Generated by Django 5.0 on 2025-05-31 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_category_car_color_car_engine_car_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='CarGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.JSONField(blank=True, default=list)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='cars.car')),
            ],
        ),
    ]
