# Generated by Django 5.0.2 on 2025-06-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_mileage_cargallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargallery',
            name='images',
        ),
        migrations.AddField(
            model_name='cargallery',
            name='gallery_url',
            field=models.URLField(default=''),
        ),
    ]
