# Generated by Django 5.0.2 on 2025-06-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_cargallery_images_cargallery_gallery_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargallery',
            name='gallery_url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
