# Generated by Django 5.0.2 on 2025-06-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_cargallery_gallery_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargallery',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
